
import Layout from "@/components/layout/Layout";

const TermsPage = () => {
  return (
    <Layout>
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
        
        <div className="prose prose-lg">
          <p>
            These Terms of Service govern your use of the 3D Price Craft website and services. 
            By using our service, you agree to these terms.
          </p>
          
          <h2>1. Service Usage</h2>
          <p>
            The pricing calculator is provided as a tool to estimate costs for 3D design services.
            All pricing is subject to final review and may be adjusted based on specific project requirements.
          </p>
          
          <h2>2. Quotations</h2>
          <p>
            Quotations generated by the calculator are valid for 30 days unless otherwise specified.
            Final pricing may be subject to change after detailed project assessment.
          </p>
          
          <h2>3. Payment</h2>
          <p>
            Payment terms will be specified in your final quote. Typically, a 50% deposit is required
            before work begins, with the remaining balance due upon project completion.
          </p>
          
          <h2>4. Intellectual Property</h2>
          <p>
            All intellectual property rights for completed projects will be transferred to the client
            upon final payment. Rights to preliminary work and unused concepts remain with 3D Price Craft.
          </p>
          
          <h2>5. Revisions</h2>
          <p>
            Standard projects include up to two rounds of revisions. Additional revisions will be billed
            at our standard hourly rate, which will be specified in your project agreement.
          </p>
          
          <h2>6. Project Timeline</h2>
          <p>
            Project timelines will be provided in your formal quote. Timelines may be extended if project
            requirements change significantly during development.
          </p>
          
          <h2>7. Cancellation</h2>
          <p>
            If a project is cancelled after work has begun, you will be invoiced for all work completed
            up to the cancellation date.
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default TermsPage;
